---
title: "NS-IBTS"
output:
  flexdashboard::flex_dashboard:
runtime: shiny
---


```{r eval = FALSE}
# TODO: Check why numbers in length plot here are different from numbers in
#       fyrirkongenekkiprest
```

```{r}
library(tidyverse)
d <- read_rds("ftp://ftp.hafro.is/pub/data/rds/nsibts-q3.rds")
d$rbyl <- d$rbyl |> mutate(sid = latin)
d$rbl <- d$rbl |> mutate(sid = latin)
d$boot <- d$boot |> mutate(sid = latin)
d$rbys <- d$rbys |> mutate(sid = latin)
d$glyph <- d$glyph |> mutate(sid = latin)
#fix this upstream?
d$rbys <-
  d$rbys |>
  group_by(latin) |>
  mutate(N = ifelse(N > quantile(N, 0.9999), quantile(N, 0.9999), N),
         B = ifelse(B > quantile(B, 0.9999), quantile(B, 0.9999), B)) |>
  ungroup()

d$prob <- d$prob |> mutate(sid = latin)
xy <- d$rbys |> select(lon, lat) |> distinct()
max.year <- max(d$rbys$year)
# source("R/functions.R")
gg_length <- function(median, by.year, SID, var, lab = "Fjöldi í hverju lengdarbili") {
  
  ggplot2::ggplot() +
    ggplot2::theme_bw(base_size = 14) +
    ggplot2::geom_ribbon(data = median %>%
                           dplyr::filter(sid == SID),
                         ggplot2::aes(length, ymax = {{ var }}, ymin = 0), fill = "grey") +
    ggplot2::geom_line(data = by.year  %>%
                         dplyr::filter(sid == SID),
                       ggplot2::aes(length, {{ var }})) +
    ggplot2::facet_wrap(~ year, dir = "v", ncol = 3, strip.position = "right") +
    ggplot2::labs(x = NULL, y = lab) +
    ggplot2::scale_x_continuous(breaks = seq(10, 200, by = 20)) +
    guides(x = guide_axis(n.dodge = 2))
  
}

gg_boot <- function(data, SID, ylab = "Fjöldi í togi") {
  data %>%
    dplyr::filter(sid == SID) %>%
    ggplot2::ggplot(ggplot2::aes(year, mean)) +
    ggplot2::theme_bw(base_size = 16) +
    ggplot2::geom_pointrange(ggplot2::aes(year, mean, ymin = lower.ci, ymax = upper.ci)) +
    ggplot2::scale_x_continuous(breaks = seq(1985, 2025, by = 5)) +
    ggplot2::expand_limits(y = 0) +
    ggplot2::labs(x = NULL, y = ylab)
}

steps <- c(-Inf, -1200, -800, -400, -150, Inf)


gg_bubble <- function(data, SID, var, lab = "Fjöldi", cl) {
  
  data <-
    data %>%
    dplyr::filter(year %in% c(2000, 
                              2001, 2002, 2003, 2004, 2005, 
                              2006, 2007, 2008, 2009, 2010, 
                              2011, 2012, 2013, 2014, 2015, 
                              2016, 2017, 2018, 2019, 2020, 
                              2021, 2022),
                  sid == SID)
  
  p <-
    ggplot() +
    theme_minimal(base_size = 12) +
    scale_x_continuous(NULL, NULL, expand = expansion(0)) +
    scale_y_continuous(NULL, NULL, expand = expansion(0)) +
    geom_polygon(data = cl, aes(lon, lat, group = group), colour = "grey", fill = "grey") +
    coord_quickmap(xlim = range(data$lon), ylim = range(data$lat)) +
    theme(panel.spacing.x=unit(0.3, "lines"),panel.spacing.y=unit(0.3, "lines"))
  
  p +
    ggplot2::geom_point(data = data,
                        ggplot2::aes(lon, lat, size = {{ var }}),
                        alpha = 0.2, colour = "red") +
    ggplot2::geom_point(data = data,
                        ggplot2::aes(lon, lat),
                        size = 0.1, colour = "blue") +
    ggplot2::scale_size_area(max_size = 30) +
    ggplot2::labs(size = lab) +
    ggplot2::facet_wrap(~ year, nrow = 3, dir = "h") 
}


scale_longitude_ices <- function(min = -44, max = 68.5, step = 1, ...) {
  breaks <- seq(min + 0.5, max - 0.5, step)
  labels <- geo::d2ir(60, breaks) %>% stringr::str_sub(3)
  return(ggplot2::scale_x_continuous(name = NULL, breaks = breaks, labels = labels, ...))
}
scale_latitude_ices <- function(min = 36, max = 84.5, step = 0.5, ...) {
  breaks <- seq(min + 0.25, max - 0.25, step)
  labels <- geo::d2ir(breaks, 0) %>% stringr::str_sub(1, 2)
  return(ggplot2::scale_y_continuous(name = NULL, breaks = breaks, labels = labels, ...))
}

glyphs <- function (data, x_major, x_minor, y_major, y_minor, polar = FALSE, 
                    height = ggplot2::rel(0.95), width = ggplot2::rel(0.95), 
                    y_scale = identity, x_scale = identity) {
  data$gid <- interaction(data[[x_major]], data[[y_major]], 
                          drop = TRUE)
  rescale01 <- function (x, xlim = NULL)  {
    if (is.null(xlim)) {
      rng <- range(x, na.rm = TRUE)
    }
    else {
      rng <- xlim
    }
    (x - rng[1])/(rng[2] - rng[1])
  }
  rescale11 <- function (x, xlim = NULL) {
    2 * rescale01(x, xlim) - 1
  }
  if (ggplot2:::is.rel(width)) {
    width <- resolution(data[[x_major]], zero = FALSE) * 
      unclass(width)
    message("Using width ", format(width, digits = 3))
  }
  if (ggplot2:::is.rel(height)) {
    height <- resolution(data[[y_major]], zero = FALSE) * 
      unclass(height)
    message("Using height ", format(height, digits = 3))
  }
  if (!identical(x_scale, identity) || !identical(y_scale, 
                                                  identity)) {
    data <- ddply(data, "gid", function(df) {
      df[[x_minor]] <- x_scale(df[[x_minor]])
      df[[y_minor]] <- y_scale(df[[y_minor]])
      df
    })
  }
  if (polar) {
    theta <- 2 * pi * rescale01(data[[x_minor]])
    r <- rescale01(data[[y_minor]])
    data$gx <- data[[x_major]] + width/2 * r * sin(theta)
    data$gy <- data[[y_major]] + height/2 * r * cos(theta)
    data <- data[order(data[[x_major]], data[[x_minor]]), 
    ]
  }
  else {
    data$gx <- data[[x_major]] + rescale11(data[[x_minor]]) * 
      width/2
    data$gy <- data[[y_major]] + rescale11(data[[y_minor]]) * 
      height/2
  }
  structure(data, width = width, height = height, polar = polar, 
            x_major = x_major, y_major = y_major, class = c("glyphplot", 
                                                            "data.frame"))
}


gg_glyph <- function(data, SID, now.year) {

  # add a year before and after


  n.glyph <-
    data |>
    dplyr::filter(sid == SID) %>%
    glyphs(x_major = "lon",
                   y_major = "lat",
                   x_minor = "year",
                   y_minor = "Y",
                   width = 1,
                   height = 0.5)

  n.glyph %>%
    dplyr::mutate(years = ifelse(between(year, 2000, 2021), "history", "current"),
                  pos = ifelse(Y != 0, TRUE, FALSE),
                  base = lat - 0.25,
                  gy = ifelse(Y == 0 & between(year, 2000, 2022), gy + 0.005, gy)) %>%
    ggplot2::ggplot() +
    ggplot2::theme_minimal() +
    ggplot2::geom_linerange(ggplot2::aes(x = gx, ymin = base, ymax = gy,
                                         colour = years)) +
    ggplot2::geom_polygon(data = d$cl, ggplot2::aes(lon, lat, group = group), fill = "grey", alpha = 0.7) +
    scale_longitude_ices() +
    scale_latitude_ices() +
    ggplot2::scale_colour_manual(values = c("history" = "#377EB8", "current" = "#E41A1C")) +
    ggplot2::theme(panel.grid.major = ggplot2::element_blank(),
                   panel.grid.minor = ggplot2::element_line(size = 1),
                   axis.ticks = ggplot2::element_blank(),
                   legend.position = "none") +
    labs(x = NULL, y = NULL)
}


species <- d$species
now.year <- max(d$rbyl$year)
```


Sidebar {.sidebar data-width=175}
=====================================

```{r}
selectInput(inputId = "Species", label = "Species:",
            choices = species, selected = "Gadus morhua")


radioButtons(inputId = "Type", label = "Choice:", 
             choices = list("Numbers", "Mass"),
             selected = list("Numbers"))
```

Trial stuff - draft explanation (in Icelandic) [here](http://www.hafro.is/~einarhj/skyringar.html).

Time
=====================================  

Column {data-width=600}
-------------------------------------

### Catch by length


```{r}
renderPlot({
  if(input$Type == "Numbers") 
  {
    gg_length(d$rbl, d$rbyl, input$Species, n, lab = "Mean numbers per tow")
  } else {
    gg_length(d$rbl, d$rbyl, input$Species, b, lab = "Mean kg per tow")
  }
})
```


Column {data-width=400}
-------------------------------------

### Mean catch and confidence intervals


```{r}
renderPlot({
  if(input$Type == "Numbers") 
  {
    gg_boot(d$boot |> filter(var == "N"), input$Species, ylab = "Numbers per hour")
  } else {
    gg_boot(d$boot |> filter(var == "B"), input$Species, ylab = "Kg per hour")  
  }
})
```

### Catch in `r max.year`

```{r}
renderPlot({
  if(input$Type == "Numbers") {
    gg_bubble(d$rbys |> filter(year == max.year), input$Species, N, cl = d$cl) + theme(legend.position = "none")
  } else {
    gg_bubble(d$rbys |> filter(year == max.year), input$Species, B, lab = "Catch [kg]", cl = d$cl) + theme(legend.position = "none")
  }
})
```

Space
=====================================

Column {.tabset}
-------------------------------------

### Catch per tow

```{r}
renderPlot({
  if(input$Type == "Numbers") {
    gg_bubble(d$rbys, input$Species, N, lab = "Numbers", cl = d$cl)
  } else {
    gg_bubble(d$rbys, input$Species, B, lab = "Catch [kg]", cl = d$cl)
  }
})
```

### Space time plot

```{r}
renderPlot({
  if(input$Type == "Numbers") {
    d$glyph |> rename(Y = N) |> gg_glyph(input$Species, now.year) + coord_quickmap(xlim = range(d$rbys$lon), ylim = range(d$rbys$lat))
  } else {
    d$glyph |> rename(Y = B) |> gg_glyph(input$Species, now.year) + coord_quickmap(xlim = range(d$rbys$lon), ylim = range(d$rbys$lat))
  }
})
```

### Probility of capture

```{r}
renderPlot({
  tmp <- 
    d$prob |> 
    filter(sid == input$Species)
  
  tmp |> 
    ggplot() +
    theme_void() +
    scale_x_continuous(expand = expansion(mult = 0)) +
    scale_y_continuous(expand = expansion(mult = 0)) +
    geom_raster(aes(lon, lat, fill = p), alpha = 0.7) +
    geom_point(data = xy, aes(lon, lat), size = 0.1, colour = "blue") +
    geom_polygon(data = d$cl, aes(lon, lat, group = group), colour = "grey", fill = "grey") +
    coord_quickmap(xlim = range(d$rbys$lon), ylim = range(d$rbys$lat)) +
    scale_fill_viridis_d(option = "B", direction = -1, drop = FALSE) +
    labs(fill = "Probability of\ncapture [%]")
})
```

About the doodle
===================================== 